### ISSUE TITLE
漢字臺羅對齊 GET 500

### ISSUE THREAD

**Issue by a8568730** [sih4sing5hong5/su5lui3-hun1kip4#12]
client.js?a54e:841 GET https://xn--lhrz38b.xn--v0qr21b.xn--kpry57d/%E6%BC%A2%E5%AD%97%E9%9F%B3%E6%…20k%C3%A1m%20%C5%AB%20si%C5%ABnn-beh%20l%C3%A2i%20tsia%20tshit-th%C3%B4%3F 500 ()

**Comment by a8568730** [comment]
kip4:漢字臺羅 SuperagentPromiseError: cannot GET https://xn--lhrz38b.xn--v0qr21b.xn--kpry57d/漢字音標對齊?%E6%9F%A5%E8%A9%A2%E8%85%94%E5%8F%A3=%E9%96%A9%E5%8D%97%E8%AA%9E&%E9%9F%B3%E6%A8%99=l%C3%ADn%20k%C3%A1m%20%C5%ABcolor: goldenrodi%C5%ABnn-beh%20l%C3%A2i%20tsia%20tshit-th%C3%B4%3F (500)
    at 漢字臺羅.proxiedMethod (eval at <anonymous> (http://localhost:3000/bundle.js:2875:2), <anonymous>:44:30)
    at new 漢字臺羅 (eval at proxyClass (eval at <anonymous> (http://localhost:3000/bundle.js:2179:2)), <anonymous>:4:17)
From previous event:
    at new 看書面 (eval at proxyClass (eval at <anonymous> (http://localhost:3000/bundle.js:2179:2)), <anonymous>:4:17)
    at Object.mountComponent (eval at <anonymous> (http://localhost:3000/bundle.js:1027:2), <anonymous>:46:35)
    at Object.mountComponent (eval at <anonymous> (http://localhost:3000/bundle.js:1027:2), <anonymous>:46:35)
    at Object.mountComponent (eval at <anonymous> (http://localhost:3000/bundle.js:1027:2), <anonymous>:46:35)%c +0ms

**Comment by sih4sing5hong5** [comment]
`服務`彼爿改矣
